version : '3'
services:
  mongodb:
    image: mongo
    container_name: groupe7_mongo
    ports:
    - 27017:27017
    volumes:
    - devmongodb:/data/db


  mysqldb:
    image: mysql
    container_name: groupe7_mysql
    environment:
      MYSQL_ROOT_PASSWORD : "rootpwd"
      MYSQL_DATABASE : "devdb"
      MYSQL_USER : "devuser"
      MYSQL_PASSWORD : "devpwd"
    ports:
    - 3306:3306
    volumes:
    - devmysqldb:/var/lib/mysql

volumes:
  devmysqldb:
  devmongodb: